// Re-export Lucide icons with custom aliases for backward compatibility
export {
	Star as IconStar,
	Image as IconImage,
	Upload as IconUpload,
	Zap as IconBolt,
	AlertCircle as IconError,
	Check as IconCheck,
	Download as IconDownload,
	Clock as IconClock,
	X as IconClose,
	Inbox as IconInbox,
	LogOut as IconLogout,
	User as IconUser,
	Lock as IconLock,
	Trash2 as IconTrash,
	Loader2 as IconLoader,
	Sun as IconSun,
	Moon as IconMoon,
	Settings as IconSettings,
	History as IconHistory,
	LayoutDashboard as IconDashboard,
	Menu as IconMenu,
	ChevronLeft as IconChevronLeft,
	Eye as IconEye,
	EyeOff as IconEyeOff
} from '@lucide/svelte';
